In [ ]:
import numpy as np
arr=np.array([10,20,30,40])
print(arr)
print(type(arr))


[10 20 30 40]
<class 'numpy.ndarray'>


numpy stands for numerical python used to perform the operation on array 
numpy is one of the most imp foundational package for numerical omputing in python 
it is an open sourse python package that is widelyy used in science and engineering 
the numpy library  contains multi dimentional array data  structure such as homogenous , n dimentional nd array
and a largge librarry of functions that operattes efficiently on these data structures


# why do we use python numpy
* we use opython numpy array instead of list bcos of the below 3 reasons 
> - less memory
> - fast
> - convinient to understand 
> - vectorisation(way faster than loop in list)

# why not python inbuilt data strructure list?
* a python list stores elements +meta data + pointer
> - uses more memory
* a numpy array stores data in continuous block
> - more efficient and compact 
*

In [ ]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr)


[[1 2 3]
 [4 5 6]]


In [ ]:
arr=np.array((4,5,6))
print(arr)


[4 5 6]


In [ ]:
arr=np.array({4,5,6})
print(arr)


{4, 5, 6}


In [ ]:
# attributes of array (functions we can use)
oned=np.array([1,2,3])
print(oned.ndim)  #dimension of array
print(oned.shape)  #shape of the array in row and  column
print(oned.size)  #size of array 
print(oned.dtype)  #data type of array
print(oned.itemsize)  #size of each element in array bytes


1
(3,)
3
int64
8


In [ ]:
# convert range to array
oned=np.array(range(1,6))
print(oned)


[1 2 3 4 5]


CREATING 2D ARRAY

In [ ]:
oned=np.array([[1,2,3],[4,5,6]])
print(oned)

print(oned.ndim)  #dimension of array
print(oned.shape)  #shape of the array in row and  column
print(oned.size)  #size of array
print(oned.dtype)  #data type of array
print(oned.itemsize)  #size of each element in array bytes


[[1 2 3]
 [4 5 6]]
2
(2, 3)
6
int64
8


CREATING 3D ARRAY

In [ ]:
oned=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(oned)

print(oned.ndim)  #dimension of array
print(oned.shape)  #shape of the array in row and  column
print(oned.size)  #size of array
print(oned.dtype)  #data type of array
print(oned.itemsize)  #size of each element in array bytes


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
3
(2, 2, 3)
12
int64
8


In [16]:
n=np.arange(1,10,2)
print(n)


[1 3 5 7 9]


In [17]:
v=np.linspace(0,90,5)
v


array([ 0. , 22.5, 45. , 67.5, 90. ])

In [18]:
import sys
li=[1,2,3,4,5]
print(sys.getsizeof(li))  
arr=np.array(li)
print(arr.size*arr.itemsize)
print(arr.nbytes)   


104
40
40


In [ ]:
import time
l1=ra


# The choice method

In [3]:
import numpy as np
rng=np.random.default_rng()
x=np.random.choice([12,3,4,5,6])
y= rng.choice([1,2,3,4,5,6],size=2)
print(x)
print(y)


4
[3 1]


# accessing 
*indexing in munpy is quite similar to python's list standard indexing 

In [8]:
x=np.array([[1,3,6],[5,3,5]])
x
print(x[0,2])
print(x[0][2])



6
6


In [ ]:
y=np.array([[22,3,543],[23,4,5],[54,56,67]])
print(y[1:])
print(y[-3,-1])
print(y)


[[23  4  5]
 [54 56 67]]
543


In [4]:
import numpy as np
xy=np.random.randint (2,100,size=(10,10))
xy1=np.random.rand(10,10)
print(xy)
print(xy1)
print(xy[:[1,3,5]])


[[10 60 36 69 46 67 33 99 11 26]
 [61 77 85 28 74 79 66 36 43 89]
 [26 47 31 99 19 28  6 25 79 78]
 [90  8 73 22 99 41 60 20 24 69]
 [39 25 95 23 58 11 30 80 22 42]
 [49 24 52 92 99 65 82 43 67 70]
 [22 21 58 76 53 26 87 87 10 58]
 [91 60 45 97 58 21 97 32  2 70]
 [54 98 23 89 66 96 94 93 19 14]
 [90 33 65 61 91 23 82 29 22 46]]
[[0.07899993 0.36231895 0.4058598  0.37089621 0.05916307 0.99174851
  0.31599631 0.69096947 0.66934236 0.76014834]
 [0.59289258 0.16292516 0.27408933 0.0394305  0.1677773  0.61569295
  0.29023588 0.17573757 0.00792976 0.31068576]
 [0.27432512 0.09662748 0.403546   0.08778667 0.84361237 0.51632756
  0.22978624 0.8752624  0.20793541 0.26261135]
 [0.35488035 0.96289886 0.77455076 0.95241187 0.40984649 0.88570104
  0.91463503 0.95198764 0.73331569 0.21859747]
 [0.27474513 0.12872754 0.74260301 0.58580416 0.88902765 0.15020673
  0.7708662  0.3625907  0.93404921 0.05578746]
 [0.48855712 0.13179066 0.70641418 0.11121077 0.40139061 0.12008897
  0.04521467 0.1633064  0.

TypeError: slice indices must be integers or None or have an __index__ method

# copy and view

In [15]:
import numpy as np
n=np.arange(1,13)
n[5]=20
print(n)
id(n)


[ 1  2  3  4  5 20  7  8  9 10 11 12]


1427195054000

In [20]:
y=n.reshape((3,4)).base
print(y)
id(y)


[ 1  2  3  4  5 20  7  8  9 10 11 12]


1427195054000

In [26]:
arr=np.array([1,2,3,3,4])
x=arr.view()
y=arr.copy()
arr[0]=42
arr[3]=100
print(arr)
id(arr)


[ 42   2   3 100   4]


1427195067056

In [27]:
print(x)
print(id(x))
print(x.base)


[ 42   2   3 100   4]
1427195066960
[ 42   2   3 100   4]


In [28]:
print(y)
print(id(y))
print(y.base)


[1 2 3 3 4]
1427195067344
None


# check if the array owns its data
* we check using .base if t returns someting thes its copied from somewhere whileif we get none means its original

# flattening of array
converting a multidim array into one d array

In [32]:
x=np.random.randint(10,size=(2,3))
print(x)
x.reshape(-1)


[[2 6 4]
 [7 8 8]]


array([2, 6, 4, 7, 8, 8], dtype=int32)

# transposing an array
special form of reshaping
that similarily returns a view on the underlying data without copying 

In [33]:
x.T


array([[2, 7],
       [6, 8],
       [4, 8]], dtype=int32)

# rotation of array
numpy.rot90(m,k=1,axes=(0,1))
m= araay f 2 or more dim
k= number of times array is rtateed by 90 deg
axes = the array is rotated inthe plane defined by axes

In [44]:
p=np.rot90(x,1,axes=(0,1))
p


array([[4, 8],
       [6, 8],
       [2, 7]], dtype=int32)